import { SYNCHRONIZE, STANDARD_RIGHTS_REQUIRED } from '../access-types'

export const THREAD_ALL_ACCESS = STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0xffff
export const THREAD_DIRECT_IMPERSONATION = 0x0200
export const THREAD_GET_CONTEXT = 0x0008
export const THREAD_IMPERSONATE = 0x0100
export const THREAD_QUERY_INFORMATION = 0x0040
export const THREAD_QUERY_LIMITED_INFORMATION = 0x0800
export const THREAD_SET_CONTEXT = 0x0010
export const THREAD_SET_INFORMATION = 0x0020
export const THREAD_SET_LIMITED_INFORMATION = 0x0400
export const THREAD_SET_THREAD_TOKEN = 0x0080
export const THREAD_SUSPEND_RESUME = 0x0002
export const THREAD_TERMINATE = 0x0001
