import { STANDARD_RIGHTS_REQUIRED, SYNCHRONIZE } from '../access-types'

export const PROCESS_ALL_ACCESS = STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0xffff
export const PROCESS_TERMINATE = 0x0001
export const PROCESS_CREATE_THREAD = 0x0002
export const PROCESS_SET_SESSIONID = 0x0004
export const PROCESS_VM_OPERATION = 0x0008
export const PROCESS_VM_READ = 0x0010
export const PROCESS_VM_WRITE = 0x0020
export const PROCESS_DUP_HANDLE = 0x0040
export const PROCESS_CREATE_PROCESS = 0x0080
export const PROCESS_SET_QUOTA = 0x0100
export const PROCESS_SET_INFORMATION = 0x0200
export const PROCESS_QUERY_INFORMATION = 0x0400
export const PROCESS_SUSPEND_RESUME = 0x0800
export const PROCESS_QUERY_LIMITED_INFORMATION = 0x1000
export const PROCESS_SET_LIMITED_INFORMATION = 0x2000
